version: '3.8'

services:
  # 1. LA BASE DE DATOS
  db:
    image: postgres:16-alpine
    container_name: dhl_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecodelivery
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  # 2. EL BACKEND (API JAVA)
  api:
    build: 
      context: ./backend
    container_name: dhl_java_api
    environment:
      - DB_HOST=db  
    ports:
      - "7070:7070"
    depends_on:
      - db
    restart: unless-stopped

  # 3. EL FRONTEND (WEB NGINX)
  web:
    build: 
      context: ./frontend
    container_name: dhl_nginx_web
    ports:
      - "8080:80"  # Entraremos a la web por el puerto 8080
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data: